### ISSUE TITLE
Items are being duplicated

### ISSUE THREAD

**Issue by thedivtagguy** [janosh/svelte-bricks#4]
Hi! Thank you for a great plugin. I am having some problem understanding the docs and rendering my image gallery correctly. I have my image data in a JSON file like so: 
```json
"images": [
        {
            "type": "image",
            "value": {
                "src": "srishti-archive-screen-1.png",
                "alt": "Site hero"
            }
        },
        {
            "type": "image",
            "value": {
                "src": "srishti-archive-screen-2.png",
                "alt": "Featured project page"
            }
        }
    ],
```
This is stored in a variable called `post`.
I then loaded your plugin:
```html
<script>
    export let post;
	let nItems = post.images.length;
	$: items = [...Array(nItems).keys()];
	let [minColWidth, maxColWidth, gap] = [400, 600, 20];
	let width, height;
</script>

<Masonry {items} {minColWidth} {maxColWidth} {gap} let:item bind:width bind:height >
			{#each post.images as image, i}
				<img
				{item}
				width="600"
						height="720"
						src="/common/assets/resources/32/{image.value.src}"
						alt="{image.value.alt}"
						srcset="/common/assets/resources/1280/{image.value.src} 1280w,
							  /common/assets/resources/960/{image.value.src} 960w,
							  /common/assets/resources/640/{image.value.src} 640w"
						sizes="(max-width: 320px) 640px, (max-width: 480px) 960px, 1280px"
						loading="lazy" />
			{/each}
		</Masonry>
```
But this gives me a gallery which looks like this: 
![image](https://user-images.githubusercontent.com/6006888/148671287-2aad2988-6bcc-4292-819c-7c8ece24906f.png)

When I change `let nItems = 1`, I get what I would like to be getting:
![image](https://user-images.githubusercontent.com/6006888/148671305-51ac2688-3331-4d2c-8f98-54f5d875f06b.png)

What am I doing wrong and how can I fix this?

**Comment by janosh** [comment]
The lines

```svelte
let nItems = post.images.length;
$: items = [...Array(nItems).keys()];
```

from the readme are just for demonstration purposes to get an array which `Masonry` can loop over. They should be replaced by your actual content, in this case `images`.

Also, you shouldn't use `#each` to loop over the items in `images` yourself. This is handled internally by `Masonry`. You only specify how to render each item by providing a child component to fill a `slot` in `Masonry`. This is what the code should look like:

```svelte
<script>
  import Masonry from 'svelte-bricks'

  const images = [
    {
      type: `image`,
      value: {
        src: `srishti-archive-screen-1.png`,
        alt: `Site hero`,
      },
    },
    {
      type: `image`,
      value: {
        src: `srishti-archive-screen-2.png`,
        alt: `Featured project page`,
      },
    },
  ]
</script>

<Masonry items={images} let:item>
  <img
    {item}
    width="600"
    height="720"
    src="/common/assets/resources/32/{item.value.src}"
    alt={item.value.alt}
    srcset="/common/assets/resources/1280/{item.value.src} 1280w,
              /common/assets/resources/960/{item.value.src} 960w,
              /common/assets/resources/640/{item.value.src} 640w"
    sizes="(max-width: 320px) 640px, (max-width: 480px) 960px, 1280px"
    loading="lazy"
  />
</Masonry>
```

**Comment by thedivtagguy** [comment]
Oh thank you so much, this has fixed it! You're developing some great things from Svelte, learning a lot from your work. Thank you again :)

**Comment by janosh** [comment]
Thanks! Will try to improve the docs at some point to make usage clearer. Maybe add an example how to render dynamically fetched images.
